apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: $joejoe
  description: $stuff
  tags:
    - python
    - etl
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: $ONSdigital/$joejoe
    backstage.io/source-template: "python-etl-template"
  links:
    - url: https://codespaces.new/$ONSdigital/$joejoe
      title: Open Development Environment 
      icon: scaffolder
    - url: https://officenationalstatistics.sharepoint.com/sites/ONS_DDaT_Communities/SitePages/SE%20-%20Principles,%20Policies,%20Guidelines%20&%20more.aspx?csf=1&web=1&share=EQI8qpmdcZ1MvVA__6yKAtgBkWCMhU-pty-SBeAs1KVAEQ&e=jlgchY
      title: Policies & Guidelines  
      icon: catalog
    - url: https://app.pluralsight.com/channels/details/c4f16af4-8278-440c-9ae8-fc9e95f1f34d
      title: Learning Pathway  
      icon: help
    - url: vscode://vscode.git/clone?url=https://github.com/$ONSdigital/$joejoe.git
      title: Open in Local Visual Studio Code
      icon: scaffolder
spec:
  type: module
  lifecycle: experimental
  owner: $
